import { useEffect, useState } from "react";
import { Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { useRouter } from "expo-router";
import { createUser, listUsers, updateUser, type LocalUser } from "@/lib/local-auth";

export default function AdminScreen() {
  const router = useRouter();
  const [users, setUsers] = useState<LocalUser[]>([]);
  const [username, setUsername] = useState(""); const [password, setPassword] = useState(""); const [name, setName] = useState(""); const [expiresAt, setExpiresAt] = useState("");
  const refresh = async () => { try { setUsers((await listUsers()).users); } catch (e) { Alert.alert("Painel", e instanceof Error ? e.message : "Não foi possível carregar os usuários."); } };
  useEffect(() => { void refresh(); }, []);
  const create = async () => { try { const result = await createUser({ username, password, name, expiresAt }); Alert.alert("Acesso criado", `Envie ao usuário:\n\nLogin: ${result.user.username}\nSenha: ${password}\nChave: ${result.licenseKey}\nVálida até: ${expiresAt}`); setUsername(""); setPassword(""); setName(""); setExpiresAt(""); await refresh(); } catch (e) { Alert.alert("Não foi possível criar", e instanceof Error ? e.message : "Revise os dados."); } };
  const renew = (user: LocalUser) => Alert.prompt?.("Renovar licença", "Informe a nova data no formato AAAA-MM-DD", async (value) => { if (!value) return; try { await updateUser(user.id, { expiresAt: value, status: "active" }); await refresh(); } catch (e) { Alert.alert("Erro", e instanceof Error ? e.message : "Não foi possível renovar."); } });
  return <ScrollView contentContainerStyle={styles.content}><Pressable onPress={() => router.back()}><Text style={styles.back}>‹ Voltar</Text></Pressable><Text style={styles.eyebrow}>ÁREA DO PROPRIETÁRIO</Text><Text style={styles.heading}>Controle de acessos</Text><Text style={styles.subtitle}>Crie credenciais e acompanhe os dispositivos autorizados. A senha é exibida somente no momento da criação.</Text><View style={styles.card}><Text style={styles.cardTitle}>Novo acesso</Text><TextInput value={name} onChangeText={setName} placeholder="Nome da pessoa (opcional)" style={styles.input} /><TextInput value={username} onChangeText={setUsername} autoCapitalize="none" placeholder="Usuário" style={styles.input} /><TextInput value={password} onChangeText={setPassword} secureTextEntry placeholder="Senha (mínimo 8 caracteres)" style={styles.input} /><TextInput value={expiresAt} onChangeText={setExpiresAt} placeholder="Vencimento: AAAA-MM-DD" style={styles.input} /><Pressable onPress={() => void create()} style={styles.primary}><Text style={styles.primaryText}>Gerar acesso e chave</Text></Pressable></View><Text style={styles.section}>USUÁRIOS AUTORIZADOS ({users.length})</Text>{users.map((user) => <View key={user.id} style={styles.userCard}><View style={{ flex: 1 }}><Text style={styles.userName}>{user.name || user.username}</Text><Text style={styles.userMeta}>@{user.username} · {user.deviceBound ? "dispositivo vinculado" : "aguardando primeiro acesso"}</Text><Text style={[styles.userMeta, user.licenseStatus === "revoked" && styles.revoked]}>Até {user.licenseExpiresAt ? new Date(user.licenseExpiresAt).toLocaleDateString("pt-BR") : "sem vencimento"} · {user.licenseStatus === "active" ? "ativa" : "revogada"}</Text></View><Pressable onPress={() => renew(user)} style={styles.small}><Text style={styles.smallText}>Renovar</Text></Pressable><Pressable onPress={async () => { await updateUser(user.id, { status: user.licenseStatus === "active" ? "revoked" : "active" }); await refresh(); }} style={[styles.small, styles.revoke]}><Text style={styles.smallText}>{user.licenseStatus === "active" ? "Bloquear" : "Ativar"}</Text></Pressable></View>)}</ScrollView>;
}
const styles = StyleSheet.create({ content: { backgroundColor: "#EAF4F8", padding: 20, paddingBottom: 60, gap: 14, flexGrow: 1 }, back: { color: "#0E8278", fontSize: 16, fontWeight: "800", marginBottom: 8 }, eyebrow: { color: "#0E8278", letterSpacing: 2.5, fontSize: 11, fontWeight: "900" }, heading: { color: "#121B24", fontSize: 30, fontWeight: "900" }, subtitle: { color: "#667580", fontSize: 14, lineHeight: 20, marginBottom: 8 }, card: { backgroundColor: "#FFF", borderRadius: 22, padding: 16, borderWidth: 1, borderColor: "#D4E0E5", gap: 9 }, cardTitle: { color: "#121B24", fontSize: 18, fontWeight: "900", marginBottom: 3 }, input: { height: 48, borderWidth: 1, borderColor: "#D4E0E5", borderRadius: 13, paddingHorizontal: 12, color: "#121B24", backgroundColor: "#FCFEFE" }, primary: { height: 50, borderRadius: 14, backgroundColor: "#0E8278", alignItems: "center", justifyContent: "center", marginTop: 5 }, primaryText: { color: "#FFF", fontWeight: "900" }, section: { color: "#667580", letterSpacing: 2, fontSize: 11, fontWeight: "900", marginTop: 10 }, userCard: { backgroundColor: "#FFF", borderRadius: 18, padding: 14, borderWidth: 1, borderColor: "#D4E0E5", flexDirection: "row", alignItems: "center", gap: 7 }, userName: { color: "#121B24", fontSize: 16, fontWeight: "900" }, userMeta: { color: "#667580", fontSize: 12, marginTop: 3 }, revoked: { color: "#A53E45" }, small: { backgroundColor: "#E5F5F2", paddingHorizontal: 9, paddingVertical: 8, borderRadius: 9 }, smallText: { color: "#0E8278", fontSize: 11, fontWeight: "900" }, revoke: { backgroundColor: "#FFF0EF" } });
