import { Alert, Image, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import * as ImagePicker from "expo-image-picker";
import { ScreenContainer } from "@/components/screen-container";
import { IconSymbol } from "@/components/ui/icon-symbol";
import { useNotificationStore } from "@/lib/notification-store";

const ink = "#121B24"; const muted = "#667580"; const teal = "#0E8278"; const border = "#D4E0E5";
export default function IconScreen() { const { selectedImage, setSelectedImage } = useNotificationStore(); const choose = async () => { const result = await ImagePicker.launchImageLibraryAsync({ mediaTypes: ["images"], allowsEditing: true, aspect: [1, 1], quality: .9 }); if (!result.canceled && result.assets[0]?.uri) await setSelectedImage(result.assets[0].uri); }; return <ScreenContainer containerClassName="bg-[#EAF4F8]"><ScrollView contentContainerStyle={styles.content}><View style={styles.header}><View><Text style={styles.eyebrow}>PERSONALIZAÇÃO</Text><Text style={styles.heading}>Ícone da notificação</Text><Text style={styles.subtitle}>Escolha a imagem que será usada no cartão e na pré-visualização.</Text></View><View style={styles.headerIcon}><IconSymbol name="bell.fill" size={32} color={teal} /></View></View><View style={styles.card}><View style={styles.imageRow}>{selectedImage ? <Image source={{ uri: selectedImage }} style={styles.image} /> : <View style={styles.image}><IconSymbol name="bell.fill" size={48} color="#FFF" /></View>}<View style={{ flex: 1 }}><Text style={styles.cardTitle}>Imagem atual</Text><Text style={styles.cardBody}>Use uma foto quadrada para obter um resultado melhor no cartão da notificação.</Text></View></View><Pressable onPress={choose} style={styles.button}><IconSymbol name="image" size={23} color="#FFF" /><Text style={styles.buttonText}>Escolher imagem</Text></Pressable></View><View style={styles.info}><IconSymbol name="info" size={24} color={teal} /><Text style={styles.infoText}>No iOS, o pequeno ícone ao lado da notificação é o ícone nativo do aplicativo. A imagem escolhida personaliza a pré-visualização e é enviada como anexo da notificação.</Text></View>{selectedImage ? <Pressable onPress={() => void setSelectedImage(undefined)}><Text style={styles.remove}>Remover imagem escolhida</Text></Pressable> : null}</ScrollView></ScreenContainer>; }
const styles = StyleSheet.create({ content: { padding: 20, paddingBottom: 40, gap: 24 }, header: { flexDirection: "row", alignItems: "flex-start", gap: 13, paddingTop: 8 }, eyebrow: { color: teal, letterSpacing: 3, fontSize: 12, fontWeight: "800" }, heading: { color: ink, fontSize: 32, fontWeight: "900", lineHeight: 38, marginTop: 4, flexShrink: 1 }, subtitle: { color: muted, fontSize: 17, lineHeight: 24, marginTop: 8, maxWidth: 280 }, headerIcon: { marginLeft: "auto", width: 78, height: 78, borderRadius: 25, backgroundColor: "#DCEFED", alignItems: "center", justifyContent: "center" }, card: { backgroundColor: "#FFF", borderRadius: 26, borderWidth: 1, borderColor: border, padding: 20, gap: 20 }, imageRow: { flexDirection: "row", alignItems: "center", gap: 18 }, image: { width: 137, height: 137, borderRadius: 25, backgroundColor: teal, alignItems: "center", justifyContent: "center" }, cardTitle: { color: ink, fontSize: 22, fontWeight: "900" }, cardBody: { color: muted, fontSize: 16, lineHeight: 24, marginTop: 6 }, button: { minHeight: 62, borderRadius: 21, backgroundColor: teal, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 10 }, buttonText: { color: "#FFF", fontSize: 19, fontWeight: "900" }, info: { borderWidth: 1, borderColor: "#B9DCD8", backgroundColor: "#E2F2F1", borderRadius: 22, padding: 20, flexDirection: "row", gap: 13, alignItems: "flex-start" }, infoText: { color: ink, flex: 1, fontSize: 15, lineHeight: 23 }, remove: { color: "#B44B47", textAlign: "center", fontWeight: "800", fontSize: 15 } });
