import { Alert, Image, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { useState } from "react";
import { ScreenContainer } from "@/components/screen-container";
import { IconSymbol } from "@/components/ui/icon-symbol";
import { useNotificationStore } from "@/lib/notification-store";

const teal = "#0E8278"; const bg = "#EAF4F8"; const ink = "#121B24"; const muted = "#667580"; const border = "#D4E0E5";
export default function ScheduleScreen() {
  const { schedule, records, selectedImage } = useNotificationStore();
  const [title, setTitle] = useState(""); const [subtitle, setSubtitle] = useState(""); const [body, setBody] = useState(""); const [minutes, setMinutes] = useState(1);
  const pending = records.filter((item) => item.status === "pending");
  const submit = async () => { if (!title.trim() || !body.trim()) { Alert.alert("Preencha a notificação", "Informe título e mensagem para agendar."); return; } await schedule({ title: title.trim(), subtitle: subtitle.trim(), body: body.trim(), imageUri: selectedImage }, minutes); Alert.alert("Notificação agendada", `Ela será emitida em ${minutes} minuto${minutes === 1 ? "" : "s"}.`); setTitle(""); setSubtitle(""); setBody(""); };
  return <ScreenContainer containerClassName="bg-[#EAF4F8]"><ScrollView contentContainerStyle={styles.content}><Text style={styles.heading}>Agendar Notificação</Text><Field label="Nome do Banco (Título)" value={title} onChangeText={setTitle} placeholder="Ex: Inter" /><Field label="Subtítulo (Opcional)" value={subtitle} onChangeText={setSubtitle} placeholder="Ex: Transação confirmada" /><Field label="Mensagem (Corpo)" value={body} onChangeText={setBody} placeholder="Ex: Você recebeu um Pix de R$ 100,00" multiline /><Text style={styles.label}>Quando enviar?</Text><View style={styles.grid}>{[1, 5, 10, 30].map((value) => <Pressable key={value} onPress={() => setMinutes(value)} style={[styles.choice, minutes === value && styles.choiceActive]}><Text style={[styles.choiceText, minutes === value && { color: "#FFF" }]}>{value} minuto{value === 1 ? "" : "s"}</Text></Pressable>)}</View><Pressable onPress={submit} style={styles.button}><IconSymbol name="calendar.badge.clock" size={24} color="#FFF" /><Text style={styles.buttonText}>Agendar Agora</Text></Pressable><Text style={styles.section}>Agendamentos pendentes</Text>{pending.length === 0 ? <View style={styles.empty}><IconSymbol name="calendar.badge.clock" size={30} color={muted} /><Text style={styles.emptyText}>Nenhum agendamento pendente.</Text></View> : pending.map((item) => <PendingCard key={item.id} item={item} />)}</ScrollView></ScreenContainer>;
}
function Field({ label, value, onChangeText, placeholder, multiline = false }: { label: string; value: string; onChangeText: (v: string) => void; placeholder: string; multiline?: boolean }) { return <View style={styles.field}><Text style={styles.label}>{label}</Text><TextInput value={value} onChangeText={onChangeText} placeholder={placeholder} placeholderTextColor="#B7C0C5" multiline={multiline} textAlignVertical={multiline ? "top" : "center"} style={[styles.input, multiline && { minHeight: 110, paddingTop: 15 }]} /></View>; }
function PendingCard({ item }: { item: import("@/lib/notification-store").NotificationRecord }) { const { cancel, remove } = useNotificationStore(); return <View style={styles.pending}><View style={styles.pendingTop}><Image source={require("@/assets/images/icon.png")} style={styles.brandImage} /><View style={{ flex: 1 }}><Text style={styles.pendingTitle}>{item.title}</Text><Text style={styles.pendingBody}>{item.body}</Text></View></View><Text style={styles.pendingDate}>{item.scheduledAt ? new Date(item.scheduledAt).toLocaleString("pt-BR") : ""}</Text><View style={styles.actions}><Pressable onPress={() => void cancel(item)} style={styles.secondary}><Text style={styles.secondaryText}>Cancelar</Text></Pressable><Pressable onPress={() => void remove(item)} style={styles.delete}><IconSymbol name="trash" size={19} color="#B44B47" /><Text style={{ color: "#B44B47", fontWeight: "800" }}>Excluir</Text></Pressable></View></View>; }
const styles = StyleSheet.create({ content: { padding: 20, paddingBottom: 40, gap: 16 }, heading: { color: ink, fontSize: 32, fontWeight: "900", marginTop: 8, marginBottom: 18 }, label: { color: ink, fontSize: 17, fontWeight: "800", marginBottom: 8 }, field: { gap: 8 }, input: { backgroundColor: "#FFF", borderWidth: 1, borderColor: border, borderRadius: 18, minHeight: 58, paddingHorizontal: 18, color: ink, fontSize: 17 }, grid: { flexDirection: "row", flexWrap: "wrap", gap: 12 }, choice: { width: "48%", minHeight: 60, borderWidth: 1, borderColor: border, borderRadius: 18, alignItems: "center", justifyContent: "center", backgroundColor: bg }, choiceActive: { backgroundColor: teal }, choiceText: { fontSize: 17, color: ink }, button: { minHeight: 64, borderRadius: 22, backgroundColor: teal, alignItems: "center", justifyContent: "center", flexDirection: "row", gap: 10, marginTop: 8 }, buttonText: { color: "#FFF", fontSize: 19, fontWeight: "900" }, section: { color: ink, fontSize: 24, fontWeight: "900", marginTop: 14 }, empty: { borderWidth: 1, borderColor: border, borderRadius: 22, padding: 24, alignItems: "center", gap: 8, backgroundColor: "#FFF" }, emptyText: { color: muted, fontSize: 16 }, pending: { backgroundColor: "#FFF", borderWidth: 1, borderColor: border, borderRadius: 22, padding: 18, gap: 11 }, pendingTop: { flexDirection: "row", gap: 12 }, pendingTitle: { color: ink, fontWeight: "800", fontSize: 17 }, pendingBody: { color: muted, fontSize: 15, marginTop: 3 }, pendingDate: { color: muted, fontSize: 13 }, actions: { flexDirection: "row", gap: 10 }, brandImage: { width: 32, height: 32, borderRadius: 10 }, secondary: { borderWidth: 1, borderColor: teal, borderRadius: 12, paddingVertical: 10, paddingHorizontal: 15 }, secondaryText: { color: teal, fontWeight: "800" }, delete: { borderWidth: 1, borderColor: "#E8B7B4", borderRadius: 12, paddingVertical: 10, paddingHorizontal: 15, flexDirection: "row", alignItems: "center", gap: 6 } });
