import { Linking, Pressable, ScrollView, StyleSheet, Switch, Text, View } from "react-native";
import { useEffect } from "react";
import * as Haptics from "expo-haptics";
import { ScreenContainer } from "@/components/screen-container";
import { IconSymbol } from "@/components/ui/icon-symbol";
import { useNotificationStore } from "@/lib/notification-store";

const ink = "#121B24"; const muted = "#667580"; const teal = "#0E8278"; const border = "#D4E0E5";
export default function SettingsScreen() { const { permission, refreshPermission, requestPermission, hapticsEnabled, setHapticsEnabled } = useNotificationStore(); useEffect(() => { const subscription = Linking.addEventListener("url", () => void refreshPermission()); return () => subscription.remove(); }, [refreshPermission]); const active = permission === "granted"; return <ScreenContainer containerClassName="bg-[#EAF4F8]"><ScrollView contentContainerStyle={styles.content}><Text style={styles.eyebrow}>CONTROLE DO APP</Text><Text style={styles.heading}>Ajustes</Text><Text style={styles.subtitle}>Preferências simples para uma experiência mais sua.</Text><Text style={styles.section}>SISTEMA</Text><View style={styles.card}><View style={styles.row}><View style={styles.iconBox}><IconSymbol name="notifications" size={29} color={teal} /></View><View style={{ flex: 1 }}><Text style={styles.cardTitle}>Permissão de notificações</Text><Text style={[styles.cardBody, { color: active ? "#3CA77A" : muted }]}>{active ? "Ativa neste dispositivo" : "Ainda não autorizada"}</Text></View><View style={[styles.status, { backgroundColor: active ? "#E4F5EF" : "#F8ECE8" }]}><View style={[styles.statusDot, { backgroundColor: active ? "#3CA77A" : "#B44B47" }]} /></View></View><View style={styles.divider} /><Pressable onPress={() => active ? void Linking.openSettings() : void requestPermission()} style={styles.settingsLink}><Text style={styles.linkText}>{active ? "Abrir Ajustes do dispositivo" : "Autorizar notificações"}</Text><IconSymbol name="arrow-up-right" size={23} color={muted} /></Pressable><Text style={styles.cardBody}>Altere a permissão quando quiser.</Text></View><Text style={styles.section}>PREFERÊNCIAS</Text><View style={styles.card}><View style={styles.row}><View style={styles.iconBox}><IconSymbol name="vibration" size={27} color={teal} /></View><View style={{ flex: 1 }}><Text style={styles.cardTitle}>Feedback tátil ao emitir</Text><Text style={styles.cardBody}>Uma resposta sutil ao concluir a ação.</Text></View><Switch value={hapticsEnabled} onValueChange={(value) => { void setHapticsEnabled(value); void Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Medium); }} trackColor={{ false: "#CBD6DA", true: "#5C9F9A" }} thumbColor="#FFF" /></View></View><View style={styles.premium}><View style={styles.premiumIcon}><IconSymbol name="bolt.fill" size={24} color="#FFF" /></View><View style={{ flex: 1 }}><Text style={styles.cardTitle}>Notificação Premium</Text><Text style={styles.cardBody}>Emissões locais, rápidas e privadas. Seus dados permanecem no aparelho.</Text></View></View><Text style={styles.version}>Versão 1.0.0</Text></ScrollView></ScreenContainer>; }
const styles = StyleSheet.create({ content: { padding: 20, paddingBottom: 40, gap: 15 }, eyebrow: { color: teal, letterSpacing: 3, fontSize: 12, fontWeight: "800", marginTop: 10 }, heading: { color: ink, fontSize: 34, fontWeight: "900" }, subtitle: { color: muted, fontSize: 17, lineHeight: 25, marginBottom: 15 }, section: { color: muted, letterSpacing: 3, fontSize: 12, fontWeight: "800", marginTop: 8 }, card: { backgroundColor: "#FFF", borderRadius: 25, borderWidth: 1, borderColor: border, padding: 20 }, row: { flexDirection: "row", alignItems: "center", gap: 14 }, iconBox: { width: 58, height: 58, borderRadius: 19, backgroundColor: "#EDF8F6", alignItems: "center", justifyContent: "center" }, cardTitle: { color: ink, fontSize: 18, fontWeight: "900" }, cardBody: { color: muted, fontSize: 16, lineHeight: 23, marginTop: 3 }, status: { width: 45, height: 45, borderRadius: 15, alignItems: "center", justifyContent: "center" }, statusDot: { width: 16, height: 16, borderRadius: 8 }, divider: { height: 1, backgroundColor: border, marginVertical: 16 }, settingsLink: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" }, linkText: { color: ink, fontSize: 16, fontWeight: "800" }, premium: { backgroundColor: "#DCEEF1", borderRadius: 25, padding: 20, flexDirection: "row", gap: 14, alignItems: "flex-start" }, premiumIcon: { width: 57, height: 57, borderRadius: 18, backgroundColor: teal, alignItems: "center", justifyContent: "center" }, version: { color: muted, textAlign: "center", marginTop: 90, fontSize: 16 } });
